#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

# crear carpetas necesarias
# crear firmas acompañantes
# mover las firmas a la carpeta
# comprimir en .tar.gz
# limpiar

echo -e "\e[00;1;92mFinished...\e[00m"
exit 0
