#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

if ! [[ -f /usr/bin/gpg ]] || [[ $(dpkg --get-selections | grep -w "gnupg" | awk '{print $1}' | head -1) != gnupg ]]; then
	if [[ "$EUID" != "0" ]]; then
		echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
		exit 1
	fi
	apt-get -q update
	apt-get -qy install gnupg gpgv
	echo "Instalacion finalizada..."
	exit 0
fi

if [[ "$EUID" = "0" ]]; then
	echo "ERROR: No debe ser root."
	exit 1
fi

if [[ -d /tmp/firmas ]]; then
	rm -rf /tmp/firmas/*
else
	mkdir -p /tmp/firmas
fi

if [[ -z $1 ]]; then
	echo "ERROR: No coloco el nombre de la persona que creara las firmas."
	echo "Ejemplo: ./xsign minombre /home/user/dir"
else
	if [[ -z $2 ]]; then	
		echo "ERROR: No coloco el directorio donde estan los archivos a firmar."
		echo "Ejemplo: ./xsign minombre /home/user/dir"
	else
		for i in $(ls $2); do
			gpg --output /tmp/firmas/$1.$i.sig --detach-sig $i
		done
		tar -czf /tmp/"$1".tar.gz /tmp/firmas/
		rm -rf /tmp/firmas/*
		echo "Firmas guardadas en /tmp/$1.tar.gz"
	fi
fi

echo "Finalizado..."
exit 0
